version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing project dependencies and ensuring Gradle wrapper is executable..."
      - chmod +x gradlew
      - ./gradlew --version

  build:
    commands:
      - ./gradlew bootJar 



cache:
  paths:
    - '/root/.gradle/caches/**/*' 
    - '/root/.gradle/wrapper/**/*'

artifacts:
  files:
    - '*.jar'
  base-directory: 'build/libs'
